BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[UserProfile] ALTER COLUMN [bio] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[UserProfile] ALTER COLUMN [link] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[UserProfile] ALTER COLUMN [avatar] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
